[workspace]
members = ["seitai", "restarter"]
default-members = ["seitai"]

[workspace.dependencies.anyhow]
version = "1.0.71"

[workspace.dependencies.serenity]
git = "https://github.com/serenity-rs/serenity.git"
branch = "next"
default-features = false
features = ["cache", "client", "gateway", "model", "native_tls_backend"]

[workspace.dependencies.tokio]
version = "1.28.2"
features = ["macros", "net", "rt-multi-thread"]
