services:
  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest

  web:
    build:
      context: .
      target: development
    tty: true
    volumes:
      - type: bind
        source: Cargo.lock
        target: /usr/src/myapp/Cargo.lock
      - type: bind
        source: Cargo.toml
        target: /usr/src/myapp/Cargo.toml
      - type: bind
        source: src
        target: /usr/src/myapp/src
    command: /bin/sh -c 'cargo run'
    environment:
      - DISCORD_TOKEN
      - VOICEVOX_HOST=voicevox
