apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seitai
spec:
  serviceName: seitai
  selector:
    matchLabels:
      app: seitai
  template:
    metadata:
      labels:
        app: seitai
    spec:
      initContainers:
        - name: resources
          image: alpine/k8s:1.27.4
          command:
            - sh
            - -c
          args:
            - |
              curl --silent https://raw.githubusercontent.com/hexium310/seitai/master/init_resource.sh | sh
          env:
            - name: VOICEVOX_HOST
              value: voicevox
          volumeMounts:
            - mountPath: /apps/resources/
              name: seitai-resources
              subPath: ./resources/
      containers:
        - name: seitai
          image: ghcr.io/hexium310/seitai:0.1.3
          env:
            - name: VOICEVOX_HOST
              value: voicevox
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: seitai-secret
                  key: token
          volumeMounts:
            - mountPath: /resources/
              name: seitai-resources
              subPath: ./resources/
        - name: restarter
          image: ghcr.io/hexium310/restarter:0.1.0
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: seitai-secret
                  key: token
      serviceAccountName: restarter
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: seitai-resources
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 2Mi
        storageClassName: managed-nfs-storage
