apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: voicevox
spec:
  serviceName: voicevox
  selector:
    matchLabels:
      app: voicevox
  template:
    metadata:
      labels:
        app: voicevox
    spec:
      containers:
        - name: voicevox
          image: voicevox/voicevox_engine:cpu-ubuntu20.04-0.14.5
          ports:
            - containerPort: 50021
          resources:
            limits:
              k8s.chitoku.jp/voicevox: "1"
            requests:
              memory: 1.25Gi
          volumeMounts:
            - mountPath: /home/user/.local/share/voicevox-engine-dev/
              name: voicevox-dictionary
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: voicevox-dictionary
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 2Mi
        storageClassName: managed-nfs-storage
