[package]
name = "seitai"
version = "0.1.0"
edition = "2021"

[dependencies.anyhow]
workspace = true

[dependencies.hyper]
version = "0.14.27"
features = ["http1", "client", "runtime"]

[dependencies.regex-lite]
version = "0.1.0"

[dependencies.tokio]
workspace = true

[dependencies.serenity]
workspace = true
features = ["builder", "collector"]

[dependencies.songbird]
git = "https://github.com/serenity-rs/songbird.git"
branch = "next"
features = ["builtin-queue"]

[dependencies.symphonia]
version = "0.5.2"
features = ["wav"]

[dependencies.url]
version = "2.4.0"
