[package]
name = "seitai"
version = "0.1.9"
edition = "2021"

[dependencies.anyhow]
workspace = true

[dependencies.indexmap]
version = "2.0.0"
features = ["serde"]

[dependencies.lazy-regex]
version = "3.0.1"
features = ["lite"]

[dependencies.regex-lite]
version = "0.1.0"

[dependencies.serenity]
workspace = true
features = ["builder", "collector"]

[dependencies.songbird]
workspace = true

[dependencies.symphonia]
version = "0.5.2"
features = ["wav"]

[dependencies.time]
workspace = true

[dependencies.tokio]
workspace = true

[dependencies.tracing]
workspace = true

[dependencies.tracing-subscriber]
workspace = true

[dependencies.uuid]
workspace = true

[dependencies.voicevox]
path = "../crates/voicevox"

[target.'cfg(target_os = "macos")'.dependencies.songbird]
workspace = true
features = ["receive"]
