name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up rust-toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Check apps errors
        run: |
          cargo check --workspace
      - name: Test
        run: |
          cargo test --workspace
      - name: Run clippy
        uses: giraffate/clippy-action@v1
        with:
          level: warning
          reporter: 'github-pr-review'
          github_token: ${{ secrets.GITHUB_TOKEN }}
